### ISSUE TITLE
About the RAM needs during training

### ISSUE THREAD

**Issue by PuYuQian** [CGATOxford/DanQ_tensorflow#2]
Hi,
Recently I try to execute the DanQ architecture,but the RAM of my computer is 24GB,it can't support the work,so I want to know how big the RAM can execute it well?
Thanks,
pu

**Comment by Acribbs** [comment]
Thanks for your issue, It has been some time since we wrote this and im not entirely sure the state of the code. Im not sure what the memory requirements were but as we wrote this to be executed on a compute cluster I would have thought that it would be higher than 24GB

**Comment by PuYuQian** [comment]
Hi,
I'm glad to receive your patient reply.Thanks.
pu
